spring:
  profiles: dev
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://10.96.92.177:3306/falcon_qa?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Soda2020.
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 3
    max-active: 20
    min-idle: 2
    validation-query: SELECT 1
  datasource2:
    url: jdbc:mysql://10.96.92.177:3306/falcon_qa?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Soda2020.
    driver-class-name: com.mysql.jdbc.Driver

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 5
        min-idle: 2
        max-wait: 10000

  jackson:
    generator:
      write_numbers_as_strings: true
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8

#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml

ldap:
  url: ldap://106.2.3.16:389
  base: dc=,dc=com
  userDn:
  password:

server:
  port: 2080

sqllogger:
  mode: oss

